name: cisland
options:
  bundleIdPrefix: com.claus.island
  deploymentTarget: "14.0"
  createIntermediateGroups: true
settings:
  base:
    CLANG_ENABLE_OBJC_WEAK: "YES"
    ENABLE_USER_SCRIPT_SANDBOXING: "NO"
    SWIFT_VERSION: 5.10
targets:
  cisland:
    type: application
    platform: macOS
    sources:
      - cisland
    resources:
      - cisland/Resources
    dependencies: []
    